kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitwatch-service
rules:
  - apiGroups: [ "apps", "extensions", "gitwatch.cbuschka.github.io" ]
    resources: [ "deployments", "repositories" ]
    verbs: [ "get", "watch", "list", "update", "patch", "delete" ]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitwatch-service
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitwatch-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitwatch-service
subjects:
  - kind: ServiceAccount
    name: gitwatch-service
    namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: gitwatch-controller
  namespace: default
spec:
  serviceAccountName: gitwatch-service
  containers:
    - image: gitwatch-controller:latest
      imagePullPolicy: IfNotPresent
      name: gitwatch-controller
  restartPolicy: Always