apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: repositories.gitwatch.cbuschka.github.io
spec:
  group: gitwatch.cbuschka.github.io
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                url:
                  type: string
  names:
    plural: repositories
    # singular name to be used as an alias on the CLI and for display
    singular: repository
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Repository
    shortNames:
      - repo